### ISSUE TITLE
Refactor website to use Hugo or Jekyll

### ISSUE THREAD

**Issue by prateekj117** [amu-oss/amu-oss.github.io#2]
### Describe the issue:
Right now, @pnijhara has simply pushed the `_site` folder. The website was originally made using Hugo. We can either use Hugo or Jekyll with the same theme. Using the min Hugo/Jekyll website will give us many benefits like writing blogs in markdown if someone else wants to collaborate, using plugins, etc.

### Proposed Solution:
GitHub Pages has good support for [Jekyll](https://jekyllrb.com/). I haven't had much experience with [Hugo](https://gohugo.io/) (Maybe @pnijhara can help in making this decision). Whoever takes up this issue, the first task is:
- [x] Search for the same theme in Jekyll/Hugo, and decide which would be the best way to go for now.
- [x] Change configurations of the theme to have info of AMU-OSS. Make it similar to the website we have right now. 
- [x] Push it and deploy it on Github Pages.

**Comment by jerrycode06** [comment]
Currently, we are using a greyscale theme on our site and I've found it on Hugo [here](https://github.com/runningstream/hugograyscale). I think we are using version 1 because version 2 has some changes now.

**Comment by pnijhara** [comment]
@jerrycode06 if you are thinking of a complete revamp, then it is good to go with version 2.

**Comment by jerrycode06** [comment]
Yup, I am doing it.

**Comment by pnijhara** [comment]
One more thing. With `hugo -D` command, you can build the website in a public folder and push the whole project (without the theme that you will clone) to GitHub. You can then set the GitHub page path (in the settings) as `amu-oss.github.io/public/`. In this way, we will have the access to the markdown files as well.

**Comment by pnijhara** [comment]
@prateekj117 all the requested changes are pushed now. As suggested by @RJ722 I have added a GitHub action for publishing the website in the `gh-pages` branch. Thank you @jerrycode06 for the help.
